In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
from sklearn.metrics.pairwise import cosine_similarity
from ast import literal_eval
from random import sample

In [2]:
#Read the files in our device by providing the path of the file to read_csv function.
credits_df=pd.read_csv(r"C:\Users\Saisree\Downloads\archive\tmdb_5000_credits.csv")
movies_df=pd.read_csv(r"C:\Users\Saisree\Downloads\archive\tmdb_5000_movies.csv")

In [3]:
movies_df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits_df.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
#Merge the two dataframes 
credits_df.columns=['id','title','cast','crew']
movies_df=movies_df.merge(credits_df,on='id')

In [6]:
movies_df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
#---------------------Recommending movies based on director,cast,crew,keywords of the inputed movie--------------------------

In [8]:
features=["cast","crew","keywords","genres"]

for feature in features:
    movies_df[feature]=movies_df[feature].apply(literal_eval)
#applying literal_eval on each and every feature.
#Before applying literal_eval type of crew is List
#after applying literal_eval type of crew is dictionary.
movies_df[features].head(10)

,cast,crew,keywords,genres
0,"[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'credit_id': '52fe48009251416c750aca23', 'de...","[{'id': 1463, 'name': 'culture clash'}, {'id':...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam..."
1,"[{'cast_id': 4, 'character': 'Captain Jack Spa...","[{'credit_id': '52fe4232c3a36847f800b579', 'de...","[{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...","[{'id': 12, 'name': 'Adventure'}, {'id': 14, '..."
2,"[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '54805967c3a36829b5002c41', 'de...","[{'id': 470, 'name': 'spy'}, {'id': 818, 'name...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam..."
3,"[{'cast_id': 2, 'character': 'Bruce Wayne / Ba...","[{'credit_id': '52fe4781c3a36847f81398c3', 'de...","[{'id': 849, 'name': 'dc comics'}, {'id': 853,...","[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam..."
4,"[{'cast_id': 5, 'character': 'John Carter', 'c...","[{'credit_id': '52fe479ac3a36847f813eaa3', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam..."
5,"[{'cast_id': 30, 'character': 'Peter Parker / ...","[{'credit_id': '52fe4252c3a36847f80151a5', 'de...","[{'id': 851, 'name': 'dual identity'}, {'id': ...","[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na..."
6,"[{'cast_id': 34, 'character': 'Flynn Rider (vo...","[{'credit_id': '52fe46db9251416c91062101', 'de...","[{'id': 1562, 'name': 'hostage'}, {'id': 2343,...","[{'id': 16, 'name': 'Animation'}, {'id': 10751..."
7,"[{'cast_id': 76, 'character': 'Tony Stark / Ir...","[{'credit_id': '55d5f7d4c3a3683e7e0016eb', 'de...","[{'id': 8828, 'name': 'marvel comic'}, {'id': ...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam..."
8,"[{'cast_id': 3, 'character': 'Harry Potter', '...","[{'credit_id': '52fe4273c3a36847f801fab1', 'de...","[{'id': 616, 'name': 'witch'}, {'id': 2343, 'n...","[{'id': 12, 'name': 'Adventure'}, {'id': 14, '..."
9,"[{'cast_id': 18, 'character': 'Bruce Wayne / B...","[{'credit_id': '553bf23692514135c8002886', 'de...","[{'id': 849, 'name': 'dc comics'}, {'id': 7002...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam..."

In [9]:
#Defining get_director function
def get_director(x):
    for i in x:
        if i["job"]=='Director':
            return i["name"]
    return np.nan

In [10]:
#defining get_list function
def get_list(x):
    if isinstance(x,list):
        names=[i["name"] for i in x]
        if len(names)>3:
            names=names[:3]
        return names
    return []

In [11]:
#getting or extracting the director name from the crew
movies_df["director"]=movies_df["crew"].apply(get_director)

#getting the first three elements for each feature.Example:getting three actor names in cast,three genres to which movie belong...
features = ["cast", "keywords", "genres"]
for feature in features:
    movies_df[feature]=movies_df[feature].apply(get_list)

In [12]:
#movies_df[['original_title', 'cast', 'director', 'keywords', 'genres']].head()
features=['original_title', 'cast', 'director', 'keywords', 'genres']
movies_df[features].head()

,original_title,cast,director,keywords,genres
0,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",James Cameron,"[culture clash, future, space war]","[Action, Adventure, Fantasy]"
1,Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",Gore Verbinski,"[ocean, drug abuse, exotic island]","[Adventure, Fantasy, Action]"
2,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",Sam Mendes,"[spy, based on novel, secret agent]","[Action, Adventure, Crime]"
3,The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]",Christopher Nolan,"[dc comics, crime fighter, terrorist]","[Action, Crime, Drama]"
4,John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",Andrew Stanton,"[based on novel, mars, medallion]","[Action, Adventure, Science Fiction]"

In [13]:
#cleaning the data =>removing white spaces
def clean_data(x):
    if isinstance(x,list):
        return [str.lower(i.replace(" ","")) for i in x]
    else:
        if isinstance(x,str):
            return str.lower(x.replace(" ",""))
        else:
            return " "

In [14]:
features=["cast","keywords","director","genres"]
for feature in features:
    movies_df[feature]=movies_df[feature].apply(clean_data)

In [15]:
features=['original_title', 'cast', 'director', 'keywords', 'genres']
movies_df[features].head()

,original_title,cast,director,keywords,genres
0,Avatar,"[samworthington, zoesaldana, sigourneyweaver]",jamescameron,"[cultureclash, future, spacewar]","[action, adventure, fantasy]"
1,Pirates of the Caribbean: At World's End,"[johnnydepp, orlandobloom, keiraknightley]",goreverbinski,"[ocean, drugabuse, exoticisland]","[adventure, fantasy, action]"
2,Spectre,"[danielcraig, christophwaltz, léaseydoux]",sammendes,"[spy, basedonnovel, secretagent]","[action, adventure, crime]"
3,The Dark Knight Rises,"[christianbale, michaelcaine, garyoldman]",christophernolan,"[dccomics, crimefighter, terrorist]","[action, crime, drama]"
4,John Carter,"[taylorkitsch, lynncollins, samanthamorton]",andrewstanton,"[basedonnovel, mars, medallion]","[action, adventure, sciencefiction]"

In [16]:
#create a “soup” containing all of the metadata information extracted to input into the count_vectorizer
def create_soup(x):
     return ' '.join(x['keywords']) + ' ' + ' '.join(x['cast']) + ' ' + x['director'] + ' ' + ' '.join(x['genres'])
    

movies_df["soup"]=movies_df.apply(create_soup,axis=1) #axis=1 => along the row
print(movies_df["soup"].head())

0    cultureclash future spacewar samworthington zo...
1    ocean drugabuse exoticisland johnnydepp orland...
2    spy basedonnovel secretagent danielcraig chris...
3    dccomics crimefighter terrorist christianbale ...
4    basedonnovel mars medallion taylorkitsch lynnc...
Name: soup, dtype: object

In [17]:
count_vectorizer=CountVectorizer(stop_words="english")
#countVectorizer counts the frequency of each word and outputs a vector containing frequencies
count_matrix=count_vectorizer.fit_transform(movies_df["soup"])
print(count_matrix.shape)
#print the shape of the count_matrix formed after vectorizing the obtained soup using countvectorizer
cosine_sim=cosine_similarity(count_matrix,count_matrix)#cosine similarity measures the theta between the vectors inputed to it.
print(cosine_sim.shape)
#print the cosine similarity shape after finding the cosine similarity between count_matrix and count_matrix
movies_df=movies_df.reset_index()
indices=pd.Series(movies_df.index,index=movies_df["original_title"])

(4803, 11520)
(4803, 4803)

In [18]:
#create a function that takes in the movie title and the cosine similarity score as input and outputs the movies similar to it.
def get_recommendations(title,cosine_sim=cosine_sim):
    idx=indices[title]
    sim_scores=list(enumerate(cosine_sim[idx]))
    sim_scores=sorted(sim_scores,key=lambda x:x[1],reverse=True)#arrange the similarity scores in descending order
    sim_scores=sim_scores[1:11] #take first 10 movies except the first one as it is the same movie that we inputed.
    movies_indices=[ind[0] for ind in sim_scores]
    movies=movies_df["original_title"].iloc[movies_indices]
    return movies

In [19]:
print("Recommendations for Avengers")
print(get_recommendations("The Avengers", cosine_sim))

Recommendations for Avengers
7                  Avengers: Age of Ultron
26              Captain America: Civil War
79                              Iron Man 2
169     Captain America: The First Avenger
174                    The Incredible Hulk
85     Captain America: The Winter Soldier
31                              Iron Man 3
33                   X-Men: The Last Stand
68                                Iron Man
94                 Guardians of the Galaxy
Name: original_title, dtype: object

In [20]:
#------------------------Recommending movies based on similarities in plot line----------------------------

In [21]:
print(movies_df["overview"])

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4798    El Mariachi just wants to play his guitar and ...
4799    A newlywed couple's honeymoon is upended by th...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4801    When ambitious New York attorney Sam is sent t...
4802    Ever since the second grade when he first saw ...
Name: overview, Length: 4803, dtype: object

In [22]:
tfidf=TfidfVectorizer(stop_words="english")
movies_df["overview"]=movies_df["overview"].fillna("")
tfidf_matrix=tfidf.fit_transform(movies_df["overview"])

#print(tfidf_matrix)
print(tfidf_matrix.shape)

(4803, 20978)

In [23]:
cosine_sim=cosine_similarity(tfidf_matrix, tfidf_matrix)
print(cosine_sim.shape)
indices = pd.Series(movies_df.index, index=movies_df["original_title"]).drop_duplicates()
print(indices.head())

(4803, 4803)
original_title
Avatar                                      0
Pirates of the Caribbean: At World's End    1
Spectre                                     2
The Dark Knight Rises                       3
John Carter                                 4
dtype: int64

In [24]:
#create a function that takes in the movie title and the cosine similarity score as input and outputs the movies similar to it
def get_recommendations(title,cosine_sim=cosine_sim):
    idx=indices[title]
    sim_scores=list(enumerate(cosine_sim[idx]))
    sim_scores=sorted(sim_scores,key=lambda x:x[1],reverse=True) #arrange the similarity scores in descending order
    sim_scores=sim_scores[1:11] #take first 10 movies except the first one as it is the same movie that we inputed. 
    movies_indices=[ind[0] for ind in sim_scores]
    movies=movies_df["original_title"].iloc[movies_indices]
    return movies

In [25]:
print("Recommendations for Avengers")
print(get_recommendations("The Avengers"))

Recommendations for Avengers
7               Avengers: Age of Ultron
3144                            Plastic
1715                            Timecop
4124                 This Thing of Ours
3311              Thank You for Smoking
3033                      The Corruptor
588     Wall Street: Money Never Sleeps
2136         Team America: World Police
1468                       The Fountain
1286                        Snowpiercer
Name: original_title, dtype: object

In [26]:
#------------------Recommending movies based on genre the user inputed--------------------

In [27]:
print("Hey there! Input a genre you wanna watch")
indices = pd.Series(movies_df["original_title"],index=movies_df.index)
movizz=pd.Series(movies_df["genres"],index=movies_df.index)
genre=str(input())
movies_list=[]
for i in range(len(movies_df["genres"])):
    if genre in movizz[i]:     #check if the inputed genre is in the list
        movies_list.append(indices[i])#if it exists recommend the movie.
print(sample(movies_list,10)) #print 10 random elements of the list.

Hey there! Input a genre you wanna watch
fantasy
['Highlander III: The Sorcerer', 'Pan', 'Twilight', 'V for Vendetta', 'Superman', 'The Mummy Returns', 'The Hunger Games', 'Special', 'Maleficent', 'Cat People']

In [28]:
#------------------Recommending movies based on director the user inputed--------------------

In [29]:
print("Hey there! pick a director you like")
indices = pd.Series(movies_df["original_title"],index=movies_df.index)
movizz=pd.Series(movies_df["director"],index=movies_df.index)
#print(movizz)
direc=str(input())
movies_list=[]
for i in range(len(movies_df["director"])):
    if direc==movizz[i]:  #check if it matches the input director
        movies_list.append(indices[i])#if matched then recommend the movie
print(movies_list)

Hey there! pick a director you like
jamescameron
['Avatar', 'Titanic', 'Terminator 2: Judgment Day', 'True Lies', 'The Abyss', 'Aliens', 'The Terminator']

In [30]:
#------------------Recommending movies based on actor the user inputed--------------------

In [31]:
print("Hey there! pick an actor you like")
indices = pd.Series(movies_df["original_title"],index=movies_df.index)
movizz=pd.Series(movies_df["cast"],index=movies_df.index)
#print(movizz)
actor=str(input())
movies_list=[]
for i in range(len(movies_df["cast"])):
    if actor in movizz[i]:  #check if the inputed actor is in the list
        movies_list.append(indices[i])#if matched then recommend the movie
print(movies_list)

Hey there! pick an actor you like
johnnydepp
["Pirates of the Caribbean: At World's End", "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Pirates of the Caribbean: On Stranger Tides', 'Alice in Wonderland', 'Alice Through the Looking Glass', 'Charlie and the Chocolate Factory', 'Dark Shadows', 'Rango', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'Public Enemies', 'The Tourist', 'Transcendence', 'Mortdecai', 'Black Mass', 'From Hell', 'Secret Window', 'The Ninth Gate', 'Donnie Brasco', "The Astronaut's Wife", 'Blow', 'Corpse Bride', 'The Imaginarium of Doctor Parnassus', 'Once Upon a Time in Mexico', 'Chocolat', 'Finding Neverland', 'Don Juan DeMarco', 'The Libertine', 'Edward Scissorhands', 'Fear and Loathing in Las Vegas', 'Ed Wood', "What's Eating Gilbert Grape"]